#download latest photon iso
#mount local
#copy ks config file
#copy in iso
#upload iso data store
#create vm (cpu, RAM, storage, network(s))
#deploy photon OS
#connect to vm
#cp authorized client string
#run updates
#set hostname
#set ip address
#set username
#set password
#(swap)

- hosts: controlplane.teekens.info
  name: deploy-vms.yml
  vars_files:
    - ../config.yml

  tasks:
    - name: Displays vars
      debug:
        msg:
          - "vSphere URL: {{ vsphere.url }}"
          - "Username:    {{ vsphere.user }}"
          - "Password:    {{ vsphere.password }}"
          - "Photon URL:  {{ photon.url }}"

    - name: Download photon OS minimal ISO
      get_url:
        url: "{{ photon.url }}"
        dest: /tmp/photon.iso
        force: yes
